service: aws-node-vue-nuxt-ssr

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment: 
    BROWSER_BASE_URL: ${self:custom.secrets.BASE_URL}
    BASE_URL: ${self:custom.secrets.BASE_URL}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  # - serverless-domain-manager
  - serverless-offline

custom:
  secrets: ${file(secrets.json)}
  apigwBinary:
    types:
      - '*/*'
  # customDomain:
  #   domainName: ${self:custom.secrets.DOMAIN}
  #   basePath: ''
  #   stage: ${self:custom.secrets.NODE_ENV}
  #   createRoute53Record: true
  #   # endpointType: 'regional'
  #   # if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`